// <auto-generated />
using System;
using Graphite.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Graphite.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260204171810_AddDiffSideToReviewThreads")]
    partial class AddDiffSideToReviewThreads
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Graphite.Domain.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorAvatar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("GitHubId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOutdated")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Line")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReviewThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GitHubId")
                        .IsUnique();

                    b.HasIndex("PullRequestId");

                    b.HasIndex("ReviewThreadId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Graphite.Domain.Models.FileDiff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Additions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Changes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Deletions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Patch")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PullRequestId");

                    b.HasIndex("PullRequestId", "Path")
                        .IsUnique();

                    b.ToTable("FileDiffs");
                });

            modelBuilder.Entity("Graphite.Domain.Models.GitHubConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeleteOldPRs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRefresh")
                        .HasColumnType("TEXT");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalAccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrivateKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RefreshIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseGitHubApp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GitHubConfigs");
                });

            modelBuilder.Entity("Graphite.Domain.Models.PullRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Additions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorAvatar")
                        .HasColumnType("TEXT");

                    b.Property<long>("ChangedFiles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChecksStatus")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Deletions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Draft")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GitHubId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMerged")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MergeableState")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MergedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceBranch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetBranch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GitHubId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("PullRequests");
                });

            modelBuilder.Entity("Graphite.Domain.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GitHubId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reviewer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewerAvatar")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GitHubId")
                        .IsUnique();

                    b.HasIndex("PullRequestId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Graphite.Domain.Models.ReviewThread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommentCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiffSide")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstCommentAuthor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstCommentBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOutdated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Line")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GitHubId")
                        .IsUnique();

                    b.HasIndex("PullRequestId");

                    b.HasIndex("State");

                    b.ToTable("ReviewThreads");
                });

            modelBuilder.Entity("Graphite.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Graphite.Domain.Models.UserFileViewedState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileDiffId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ViewedState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileDiffId");

                    b.HasIndex("UserId", "FileDiffId")
                        .IsUnique();

                    b.ToTable("UserFileViewedStates");
                });

            modelBuilder.Entity("Graphite.Domain.Models.UserPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommentsPanelWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiffViewMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("FileTreeVisible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileTreeWidth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Graphite.Domain.Models.Comment", b =>
                {
                    b.HasOne("Graphite.Domain.Models.PullRequest", null)
                        .WithMany("Comments")
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graphite.Domain.Models.ReviewThread", "ReviewThread")
                        .WithMany("Comments")
                        .HasForeignKey("ReviewThreadId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ReviewThread");
                });

            modelBuilder.Entity("Graphite.Domain.Models.FileDiff", b =>
                {
                    b.HasOne("Graphite.Domain.Models.PullRequest", "PullRequest")
                        .WithMany()
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PullRequest");
                });

            modelBuilder.Entity("Graphite.Domain.Models.Review", b =>
                {
                    b.HasOne("Graphite.Domain.Models.PullRequest", "PullRequest")
                        .WithMany("Reviews")
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PullRequest");
                });

            modelBuilder.Entity("Graphite.Domain.Models.ReviewThread", b =>
                {
                    b.HasOne("Graphite.Domain.Models.PullRequest", "PullRequest")
                        .WithMany("ReviewThreads")
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PullRequest");
                });

            modelBuilder.Entity("Graphite.Domain.Models.UserFileViewedState", b =>
                {
                    b.HasOne("Graphite.Domain.Models.FileDiff", "FileDiff")
                        .WithMany("UserViewStates")
                        .HasForeignKey("FileDiffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Graphite.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileDiff");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Graphite.Domain.Models.UserPreferences", b =>
                {
                    b.HasOne("Graphite.Domain.Models.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("Graphite.Domain.Models.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Graphite.Domain.Models.FileDiff", b =>
                {
                    b.Navigation("UserViewStates");
                });

            modelBuilder.Entity("Graphite.Domain.Models.PullRequest", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ReviewThreads");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Graphite.Domain.Models.ReviewThread", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Graphite.Domain.Models.User", b =>
                {
                    b.Navigation("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
