apiVersion: v1
kind: Service
metadata:
  name: git-buddy-api
  namespace: git-buddy
spec:
  selector:
    app: git-buddy-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
