apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-buddy-postgres-pvc
  namespace: git-buddy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: default
