// <auto-generated />
using System;
using GitBuddy.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GitBuddy.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260327085139_InitialCreate_PostgreSQL")]
    partial class InitialCreate_PostgreSQL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GitBuddy.Domain.Models.AllowedUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedRole")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("GitHubUsername")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Email");

                    b.HasIndex("GitHubUsername");

                    b.ToTable("AllowedUsers");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.CheckRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Conclusion")
                        .HasColumnType("text");

                    b.Property<string>("GitHubId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GitHubId")
                        .IsUnique();

                    b.HasIndex("PullRequestId");

                    b.ToTable("CheckRuns");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthorAvatar")
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EditCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GitHubId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsOutdated")
                        .HasColumnType("boolean");

                    b.Property<int?>("Line")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReplyToCommentId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReviewThreadId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GitHubId")
                        .IsUnique();

                    b.HasIndex("PullRequestId");

                    b.HasIndex("ReplyToCommentId");

                    b.HasIndex("ReviewThreadId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.CommentDraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReviewThreadId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PullRequestId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "PullRequestId", "ReviewThreadId", "FilePath", "LineNumber")
                        .IsUnique();

                    b.ToTable("CommentDrafts");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reaction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("CommentId", "Username", "Reaction")
                        .IsUnique();

                    b.ToTable("CommentReactions");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.CommentTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsOrganizationTemplate")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsOrganizationTemplate");

                    b.HasIndex("UserId");

                    b.ToTable("CommentTemplates");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.FileDiff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Additions")
                        .HasColumnType("integer");

                    b.Property<int>("Changes")
                        .HasColumnType("integer");

                    b.Property<int>("Deletions")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("OldPath")
                        .HasColumnType("text");

                    b.Property<string>("Patch")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PullRequestId");

                    b.HasIndex("PullRequestId", "Path")
                        .IsUnique();

                    b.ToTable("FileDiffs");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.GitHubConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DeleteOldPRs")
                        .HasColumnType("boolean");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastRefresh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalAccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrivateKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RefreshIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("UseGitHubApp")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("GitHubConfigs");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AcceptedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("AssignedRole")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GitHubUsername")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Email");

                    b.HasIndex("GitHubUsername");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.PendingComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Line")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PendingReviewId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PendingReviewId");

                    b.HasIndex("PendingReviewId", "Path", "Line");

                    b.ToTable("PendingComments");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.PendingReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GitHubReviewId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GitHubReviewId");

                    b.HasIndex("UserId");

                    b.HasIndex("PullRequestId", "UserId")
                        .IsUnique();

                    b.ToTable("PendingReviews");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.PullRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Additions")
                        .HasColumnType("bigint");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthorAvatar")
                        .HasColumnType("text");

                    b.Property<long>("ChangedFiles")
                        .HasColumnType("bigint");

                    b.Property<string>("ChecksStatus")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentApprovingReviews")
                        .HasColumnType("integer");

                    b.Property<long>("Deletions")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Draft")
                        .HasColumnType("boolean");

                    b.Property<long>("GitHubId")
                        .HasColumnType("bigint");

                    b.Property<bool>("HasUnresolvedThreads")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMergeReady")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMerged")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MergeBlockReason")
                        .HasColumnType("text");

                    b.Property<string>("MergeableState")
                        .HasColumnType("text");

                    b.Property<DateTime?>("MergedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RequiredApprovingReviews")
                        .HasColumnType("integer");

                    b.Property<string>("SourceBranch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetBranch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GitHubId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("PullRequests");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.RepositoryRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchPattern")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RequiredApprovingReviewCount")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresApprovingReviews")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresStatusChecks")
                        .HasColumnType("boolean");

                    b.Property<string>("RulesetName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LastSyncedAt");

                    b.HasIndex("Repository", "BranchPattern")
                        .IsUnique();

                    b.ToTable("RepositoryRules");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GitHubId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("Reviewer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReviewerAvatar")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GitHubId")
                        .IsUnique();

                    b.HasIndex("PullRequestId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.ReviewThread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiffSide")
                        .HasColumnType("integer");

                    b.Property<string>("FirstCommentAuthor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstCommentBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GitHubId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsOutdated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<int?>("Line")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PullRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GitHubId")
                        .IsUnique();

                    b.HasIndex("PullRequestId");

                    b.HasIndex("State");

                    b.ToTable("ReviewThreads");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("InvitationId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PersonalAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderUserId")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("InvitationId")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.UserFileViewedState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FileDiffId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("ViewedState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FileDiffId");

                    b.HasIndex("UserId", "FileDiffId")
                        .IsUnique();

                    b.ToTable("UserFileViewedStates");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.UserPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentsPanelWidth")
                        .HasColumnType("integer");

                    b.Property<string>("DiffViewMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("FileTreeVisible")
                        .HasColumnType("boolean");

                    b.Property<int>("FileTreeWidth")
                        .HasColumnType("integer");

                    b.Property<string>("ListViewMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.AllowedUser", b =>
                {
                    b.HasOne("GitBuddy.Domain.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.CheckRun", b =>
                {
                    b.HasOne("GitBuddy.Domain.Models.PullRequest", "PullRequest")
                        .WithMany("CheckRuns")
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PullRequest");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.Comment", b =>
                {
                    b.HasOne("GitBuddy.Domain.Models.PullRequest", null)
                        .WithMany("Comments")
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GitBuddy.Domain.Models.Comment", "ReplyToComment")
                        .WithMany("Replies")
                        .HasForeignKey("ReplyToCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GitBuddy.Domain.Models.ReviewThread", "ReviewThread")
                        .WithMany("Comments")
                        .HasForeignKey("ReviewThreadId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ReplyToComment");

                    b.Navigation("ReviewThread");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.CommentDraft", b =>
                {
                    b.HasOne("GitBuddy.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.CommentReaction", b =>
                {
                    b.HasOne("GitBuddy.Domain.Models.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.CommentTemplate", b =>
                {
                    b.HasOne("GitBuddy.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.FileDiff", b =>
                {
                    b.HasOne("GitBuddy.Domain.Models.PullRequest", "PullRequest")
                        .WithMany()
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PullRequest");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.Invitation", b =>
                {
                    b.HasOne("GitBuddy.Domain.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.PendingComment", b =>
                {
                    b.HasOne("GitBuddy.Domain.Models.PendingReview", "PendingReview")
                        .WithMany("PendingComments")
                        .HasForeignKey("PendingReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PendingReview");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.PendingReview", b =>
                {
                    b.HasOne("GitBuddy.Domain.Models.PullRequest", "PullRequest")
                        .WithMany()
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GitBuddy.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PullRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.Review", b =>
                {
                    b.HasOne("GitBuddy.Domain.Models.PullRequest", "PullRequest")
                        .WithMany("Reviews")
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PullRequest");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.ReviewThread", b =>
                {
                    b.HasOne("GitBuddy.Domain.Models.PullRequest", "PullRequest")
                        .WithMany("ReviewThreads")
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PullRequest");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.User", b =>
                {
                    b.HasOne("GitBuddy.Domain.Models.Invitation", "Invitation")
                        .WithOne()
                        .HasForeignKey("GitBuddy.Domain.Models.User", "InvitationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Invitation");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.UserFileViewedState", b =>
                {
                    b.HasOne("GitBuddy.Domain.Models.FileDiff", "FileDiff")
                        .WithMany("UserViewStates")
                        .HasForeignKey("FileDiffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GitBuddy.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileDiff");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.UserPreferences", b =>
                {
                    b.HasOne("GitBuddy.Domain.Models.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("GitBuddy.Domain.Models.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.Comment", b =>
                {
                    b.Navigation("Reactions");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.FileDiff", b =>
                {
                    b.Navigation("UserViewStates");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.PendingReview", b =>
                {
                    b.Navigation("PendingComments");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.PullRequest", b =>
                {
                    b.Navigation("CheckRuns");

                    b.Navigation("Comments");

                    b.Navigation("ReviewThreads");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.ReviewThread", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("GitBuddy.Domain.Models.User", b =>
                {
                    b.Navigation("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
